server:
  port: 8081
logging.level: DEBUG

application:
  name: Developers Corner
  
  
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/developers-corner
  username: mojibmohammad
  password: mojibmohammad
hibernate: 
  dialect: org.hibernate.dialect.MYSQLDialect
  show_sql: false
  format_sql: false